# Source Registry with Evidence Claims
# Schema: schemas/sources.schema.yml (v2)
#
# Each source contains specific claims that back specific rules.
# This creates an auditable evidence chain: source → claim → rule

# =============================================================================
# GENERIC - Applies to all agents
# =============================================================================

generic:
  - id: agents-md-spec
    title: "AGENTS.md Specification"
    url: "https://agents.md/"
    type: official
    weight: 1.0
    accessed: "2026-01-28"
    claims:
      - id: root-placement
        text: "Create an AGENTS.md file at the root of the repository"
        quote: true
        section: "Getting Started"
        rules: [S1, C1]
      - id: standard-markdown
        text: "AGENTS.md is just standard Markdown. Use any headings you like"
        quote: true
        section: "FAQ"
        rules: [S5]
      - id: nested-monorepo
        text: "Create nested AGENTS.md files for subprojects in monorepos"
        section: "Monorepos"
        rules: [S2, CLAUDE_S2]
      - id: nearest-precedence
        text: "Agents automatically read the nearest file in the directory tree, so the closest one takes precedence"
        quote: true
        section: "Monorepos"
        rules: [CLAUDE_S3]
      - id: chat-overrides
        text: "Explicit user chat prompts override everything"
        quote: true
        section: "Conflict Resolution"
        rules: [C2]
      - id: executable-commands
        text: "Agents will attempt to execute relevant programmatic checks and fix failures before finishing the task when commands are listed"
        section: "Execution Behavior"
        rules: [C1, E1]
      - id: living-document
        text: "Treat AGENTS.md as living documentation that can be updated anytime"
        section: "Maintenance"
        rules: [M1, M2]
      - id: recommended-sections
        text: "Popular sections include: project overview, build/test commands, code style, testing, security, commit/PR guidelines, deployment"
        section: "Structure"
        rules: [C1, C9]

  - id: keepachangelog
    url: "https://keepachangelog.com/en/1.1.0/"
    type: official
    weight: 1.0
    claims:
      - id: unreleased-section
        text: "Use UNRELEASED section for changes not yet in a release"
        rules: []

  - id: advanced-context-engineering
    url: "https://github.com/humanlayer/advanced-context-engineering-for-coding-agents"
    type: research
    weight: 0.8
    claims:
      - id: context-target
        text: "Target 40-60% context utilization for optimal performance"
        rules: [E8]
      - id: frequent-compaction
        text: "Use Frequent Intentional Compaction for large codebases"
        rules: [E8]

  - id: instruction-limits-principles
    url: "https://www.humanlayer.dev/blog/writing-a-good-claude-md"
    type: community
    weight: 0.4
    claims:
      - id: instruction-capacity
        text: "Frontier LLMs follow ~150-200 instructions with reasonable consistency"
        quote: true
        rules: [S1, C7]
      - id: line-limit
        text: "Less than 300 lines is optimal; shorter performs better"
        rules: [S1]
      - id: less-is-more
        text: "Less instructions is more - excessive instructions degrade quality uniformly"
        rules: [S1, C7]
      - id: use-linters
        text: "Exclude code style guidelines - use linters instead"
        rules: [E1]
      - id: progressive-files
        text: "Separate task-specific instructions into discrete markdown files"
        rules: [S2, C3]

  - id: spec-writing-for-agents
    url: "https://addyosmani.com/blog/good-spec/"
    type: community
    weight: 0.4
    claims:
      - id: three-tier-boundaries
        text: "Use three-tier boundaries: Always do, Ask first, Never do"
        rules: [C4, C10]
      - id: commands-early
        text: "Put executable commands early - full commands with flags"
        quote: true
        rules: [C1]
      - id: code-snippet-beats-prose
        text: "One real code snippet showing your style beats three paragraphs"
        quote: true
        rules: [C8]
      - id: curse-of-instructions
        text: "Performance degrades when too many rules compete for attention"
        rules: [S1, C7]
      - id: modularity
        text: "Break specs into focused sections rather than monolithic prompts"
        rules: [S2, C3]

  - id: jetbrains-junie-guidelines
    url: "https://blog.jetbrains.com/idea/2025/05/coding-guidelines-for-your-ai-agents/"
    type: official
    weight: 1.0
    claims:
      - id: guidelines-structure
        text: "Use .junie/guidelines.md for IDE-specific agent configuration"
        rules: []

# =============================================================================
# REPORAILS - Framework methodology
# =============================================================================

reporails:
  - id: capability-levels
    url: "docs/capability-levels.md"
    type: methodology
    weight: 0.6
    claims:
      - id: l6-backbone
        text: "L6 projects require backbone.yml with maps, contracts, quick_ref sections"
        rules: [S4]
      - id: l6-session-ritual
        text: "L6 requires explicit session start ritual with numbered steps"
        rules: [E2]
      - id: l6-contracts
        text: "L6 backbone includes contracts section for architecture enforcement"
        rules: [G4, G5]
      - id: l6-maps
        text: "L6 maps section includes components and platform keys"
        rules: [S4]
      - id: l6-staleness
        text: "L6 requires map staleness prevention - paths must exist"
        rules: [M5]
      - id: l6-arch-tests
        text: "L6 requires architecture tests for contract enforcement"
        rules: [G6]
      - id: methodology-threshold-emphasis
        text: "Limit IMPORTANT/CRITICAL to 5 per file to maintain impact"
        rules: [C7]
      - id: methodology-threshold-code-blocks
        text: "Code blocks should stay under 10 lines"
        rules: [E6, S3]
      - id: methodology-threshold-imports
        text: "Root file should have under 10 @imports"
        rules: [E7]
      - id: methodology-skill-size
        text: "SKILL.md files should stay under 100 lines"
        rules: [CLAUDE_S1]
      - id: methodology-rule-body
        text: "Rule file body should stay under 40 lines"
        rules: [CLAUDE_M2]

# =============================================================================
# CLAUDE - Claude Code specific
# =============================================================================

claude:
  - id: claude-code-best-practices
    url: "https://www.anthropic.com/engineering/claude-code-best-practices"
    type: official
    weight: 1.0
    claims:
      - id: keep-concise
        text: "Keep CLAUDE.md files concise and human-readable"
        quote: true
        section: "Create CLAUDE.md files"
        rules: [S1]
      - id: no-required-format
        text: "There's no required format for CLAUDE.md files"
        quote: true
        section: "Create CLAUDE.md files"
        rules: [C1]
      - id: iterative-refinement
        text: "Treat as frequently-used prompts requiring optimization"
        section: "Tune your CLAUDE.md files"
        rules: [M2]
      - id: emphasis-words
        text: "Use emphasis with IMPORTANT or YOU MUST to improve adherence"
        quote: true
        section: "Tune your CLAUDE.md files"
        rules: [C7]
      - id: include-commands
        text: "Include bash commands with descriptions"
        section: "Create CLAUDE.md files"
        rules: [C1]
      - id: include-core-files
        text: "Include core files and utility functions"
        section: "Create CLAUDE.md files"
        rules: [C1, C9]
      - id: root-placement
        text: "Place in root directory and check into git for team access"
        section: "Create CLAUDE.md files"
        rules: [M1]
      - id: version-control
        text: "Check CLAUDE.md into version control for team sharing"
        section: "Create CLAUDE.md files"
        rules: [M1]

  - id: claude-code-memory
    url: "https://code.claude.com/docs/en/memory"
    type: official
    weight: 1.0
    claims:
      - id: memory-hierarchy
        text: "Four memory locations in hierarchical structure: managed, project, rules, user"
        section: "Determine memory type"
        rules: [CLAUDE_S2]
      - id: rules-directory
        text: "Use .claude/rules/ for modular, topic-specific project instructions"
        quote: true
        section: "Modular rules"
        rules: [CLAUDE_S2, CLAUDE_S3]
      - id: path-scoped-rules
        text: "Rules can be scoped to specific files using YAML frontmatter with paths field"
        section: "Path-specific rules"
        rules: [CLAUDE_S3]
      - id: imports-syntax
        text: "CLAUDE.md files can import additional files using @path/to/import syntax"
        section: "CLAUDE.md imports"
        rules: [S2, C11]
      - id: import-max-depth
        text: "Imported files can recursively import with max-depth of 5 hops"
        section: "CLAUDE.md imports"
        rules: [E7]
      - id: local-md-gitignore
        text: "CLAUDE.local.md files are automatically added to .gitignore"
        section: "Determine memory type"
        rules: []
      - id: recursive-discovery
        text: "Claude reads memories recursively from cwd up to root"
        section: "How Claude looks up memories"
        rules: [S2]
      - id: be-specific
        text: "Be specific: Use 2-space indentation is better than Format code properly"
        quote: true
        section: "Memory best practices"
        rules: [C2]
      - id: use-structure
        text: "Format memories as bullet points grouped under descriptive headings"
        section: "Memory best practices"
        rules: [S5, C1]
      - id: review-periodically
        text: "Review memories periodically as your project evolves"
        section: "Memory best practices"
        rules: [M2]
      - id: keep-rules-focused
        text: "Keep rules focused: Each file should cover one topic"
        quote: true
        section: "Best practices"
        rules: [C3, C6]

  - id: claude-code-hooks
    url: "https://code.claude.com/docs/en/hooks-guide"
    type: official
    weight: 1.0
    claims:
      - id: hooks-for-formatting
        text: "Use hooks for automatic formatting - run prettier, gofmt after file edits"
        section: "Example use cases"
        rules: [E1]
      - id: hooks-deterministic
        text: "Hooks provide deterministic control ensuring actions always happen"
        section: "Introduction"
        rules: [E1]
      - id: app-level-code
        text: "Encode rules as hooks rather than prompting instructions for guaranteed execution"
        section: "Introduction"
        rules: [E1]

  - id: claude-code-settings
    url: "https://code.claude.com/docs/en/settings"
    type: official
    weight: 1.0
    claims:
      - id: rules-dir-config
        text: ".claude/rules/ directory configuration for path scoping"
        rules: [CLAUDE_S2, CLAUDE_S3]
      - id: settings-hierarchy
        text: "Settings follow hierarchy with managed settings taking precedence"
        rules: [CLAUDE_G1]

  - id: claude-context-windows
    url: "https://platform.claude.com/docs/en/build-with-claude/context-windows"
    type: official
    weight: 1.0
    claims:
      - id: context-awareness
        text: "Claude can track remaining context window throughout conversation"
        section: "Context awareness"
        rules: [E8]
      - id: avoid-token-warnings
        text: "Model handles context automatically - avoid redundant token warnings"
        rules: [E8]

  - id: using-claude-md-files
    url: "https://claude.com/blog/using-claude-md-files"
    type: official
    weight: 1.0
    claims:
      - id: usage-patterns
        text: "CLAUDE.md usage patterns and practical examples"
        rules: [C1, C9]
      - id: customized-content
        text: "Customize CLAUDE.md with project-specific content"
        rules: [CLAUDE_M1]

  - id: anthropic-teams-claude-code
    url: "https://claude.com/blog/how-anthropic-teams-use-claude-code"
    type: official
    weight: 1.0
    claims:
      - id: team-onboarding
        text: "New hires feed Claude codebase to get productive quickly via CLAUDE.md files"
        rules: [C9]
      - id: automated-pr-comments
        text: "Automated PR comments through GitHub Actions with Claude handling formatting"
        rules: [G7]
      - id: test-driven-guidance
        text: "Guide Claude through test-driven development with periodic checkpoints"
        rules: [M2]
      - id: governance-roles
        text: "Teams need clear roles and responsibilities for instruction files"
        rules: [G1, G3]
      - id: review-process
        text: "Implement review process for instruction file changes"
        rules: [M2, M3]

  - id: claude-4-best-practices
    url: "https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-4-best-practices"
    type: official
    weight: 1.0
    claims:
      - id: be-explicit
        text: "Be explicit with instructions - specify desired output clearly"
        section: "Be explicit"
        rules: [C2]
      - id: context-improves
        text: "Add context or motivation behind instructions to improve performance"
        section: "Add context"
        rules: [C5, C8]
      - id: never-with-context
        text: "NEVER use ellipses is less effective than explaining why (TTS engine)"
        section: "Add context"
        rules: [C10, C5]
      - id: avoid-overengineering
        text: "Avoid over-engineering - only make changes directly requested"
        section: "Minimize overengineering"
        rules: []
      - id: investigate-before-answering
        text: "Never speculate about code you have not opened"
        quote: true
        section: "Code exploration"
        rules: [E3, E4]
      - id: instructions-not-philosophy
        text: "Frame instructions with actionable modifiers, not abstract principles"
        rules: [C8]

  - id: claude-code-issue-13579
    url: "https://github.com/anthropics/claude-code/issues/13579"
    type: research
    weight: 0.8
    claims:
      - id: token-waste-measured
        text: "700K+ tokens wasted across 2M token project from 7 patterns"
        section: "Analysis Results"
        rules: [E8, S1]
      - id: check-first-build-second
        text: "CHECK FIRST, BUILD SECOND - grep costs 100 tokens vs 70K rebuild"
        section: "Golden Rules"
        rules: [E5]
      - id: grep-over-agent
        text: "grep -r costs 100 tokens, 2 sec vs Explore-Agent 40K tokens, 5 min"
        quote: true
        section: "Golden Rules"
        rules: [E5]
      - id: test-immediately
        text: "Write 1 file, test, continue (10K) vs Write 10 files, test (124K)"
        section: "Golden Rules"
        rules: []
      - id: purpose-based-reading
        text: "Read files based on purpose to minimize token usage"
        rules: [E3]
      - id: memory-reference
        text: "Reference from memory instead of re-reading unchanged files"
        rules: [E4]

  - id: claude-md-optimization-study
    url: "https://arize.com/blog/claude-md-best-practices-learned-from-optimizing-claude-code-with-prompt-learning/"
    type: research
    weight: 0.8
    claims:
      - id: optimization-improvement
        text: "+5.19% general improvement, +10.87% repo-specific from optimization"
        rules: [S1, C1]
      - id: iterative-tuning
        text: "CLAUDE.md files benefit from iterative refinement and testing"
        rules: [M2]

  - id: monorepo-claude-md-organization
    url: "https://dev.to/anvodev/how-i-organized-my-claudemd-in-a-monorepo-with-too-many-contexts-37k7"
    type: community
    weight: 0.4
    claims:
      - id: reduction-achieved
        text: "Reduced 47k to 9k words (~80%) through hierarchical structure"
        rules: [S1, S2]
      - id: service-specific-files
        text: "Use service-specific instruction files in monorepos"
        rules: [C3, S2]

  - id: enterprise-claude-usage
    url: "https://blog.sshh.io/p/how-i-use-every-claude-code-feature"
    type: community
    weight: 0.4
    claims:
      - id: kb-limit
        text: "13KB limit observed for effective instruction following"
        rules: [S1]
      - id: never-with-alternative
        text: "NEVER statements should include positive alternatives"
        rules: [C10]
      - id: engineer-threshold
        text: "30% engineer threshold - Claude handles implementation, human reviews"
        rules: []

  - id: claude-md-guide
    url: "https://www.builder.io/blog/claude-md-guide"
    type: community
    weight: 0.4
    claims:
      - id: file-placement
        text: "CLAUDE.md placement affects scope and team access"
        rules: [S2, M1]
      - id: practical-examples
        text: "Include practical examples in instruction files"
        rules: [C1]

  - id: rules-directory-mechanics
    url: "https://claudefa.st/blog/guide/mechanics/rules-directory"
    type: community
    weight: 0.4
    claims:
      - id: rules-mechanics
        text: ".claude/rules/ mechanics with path scoping and YAML frontmatter"
        rules: [CLAUDE_S2, CLAUDE_S3]
      - id: loading-behavior
        text: "Rules load based on path matching during file operations"
        rules: [CLAUDE_S3]

# =============================================================================
# COPILOT - GitHub Copilot specific
# =============================================================================

copilot:
  - id: copilot-custom-instructions
    url: "https://docs.github.com/en/copilot/customizing-copilot/adding-custom-instructions-for-github-copilot"
    type: official
    weight: 1.0
    claims:
      - id: copilot-instructions-setup
        text: "copilot-instructions.md setup for custom instructions"
        rules: []
      - id: path-specific
        text: "Path-specific instructions for different code areas"
        rules: []

# =============================================================================
# CODEX - OpenAI Codex specific
# =============================================================================

codex:
  - id: codex-agents-md
    url: "https://developers.openai.com/codex/guides/agents-md"
    type: official
    weight: 1.0
    claims:
      - id: agents-md-structure
        text: "AGENTS.md structure with 32KB limit"
        rules: [S1]
      - id: override-hierarchy
        text: "Override hierarchy for nested instruction files"
        rules: [S2]

# =============================================================================
# CURSOR - Cursor specific
# =============================================================================

cursor:
  - id: cursor-rules
    url: "https://cursor.com/docs/context/rules"
    type: official
    weight: 1.0
    claims:
      - id: cursor-rules-structure
        text: ".cursor/rules/ structure with glob patterns"
        rules: []
      - id: team-rules
        text: "Team rules sharing mechanism"
        rules: []
